### PR TITLE
Enable xdebug for composer.

### PR DESCRIPTION
**Pull request by leonhelmus**

### CODE REVIEW

**Comment by ksangers** [comment]
@leonhelmus What is this for?

**Comment by leonhelmus** [comment]
It will enable you to xdebug composer otherwise you can't.

**Comment by ksangers** [comment]
@leonhelmus That sounds good to have as an option. It should be disabled by default, right?

**Comment by leonhelmus** [comment]
@ksangers  good one.

**Review by ksangers — CHANGES_REQUESTED** [review]
Please update the `version: 1.0.0` to a new version in the templates/magento-2/docker-compose.yml file. So people using this template can see they need to update the template.

**Review by ksangers — APPROVED** [review]

**Pull request merged**
